name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv pytest pytest-cov ruff pyyaml

      - name: Run linter and tests
        run: |
          make check
          make test-coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Nataly773_python-project-502
            -Dsonar.organization=nataly773
            -Dsonar.python.coverage.reportPaths=coverage.xml